pruebatoken

diff --git a/.github/workflows/azure-static-web-apps-gray-ocean-0e2a3de0f.yml b/.github/workflows/azure-static-web-apps-gray-ocean-0e2a3de0f.yml
--- a/.github/workflows/azure-static-web-apps-gray-ocean-0e2a3de0f.yml
+++ b/.github/workflows/azure-static-web-apps-gray-ocean-0e2a3de0f.yml
@@ -27,7 +27,19 @@ jobs:
           
       - name: Install dependencies
         run: npm ci
-        
+      
+      - name: Verify Azure Token
+        run: |
+          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E2A3DE0F }}" ]; then
+            echo "❌ Token is empty or not found"
+            exit 1
+          else
+            echo "✅ Token is present (length: ${#AZURE_TOKEN})"
+          fi
+        env:
+          AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E2A3DE0F }}
+
+
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
